# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  omniauth_provider_key:    <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  twitter_omniauth_key:     <%= ENV["twitter_omniauth_key"] %>
  twitter_omniauth_secret:  <%= ENV["twitter_omniauth_secret"] %>
  tumblr_omniauth_key:    <%= ENV["tumblr_omniauth_key"] %>
  tumblr_omniauth_secret: <%= ENV["tumblr_omniauth_secret"] %>
  domain_name: example.com
  secret_key_base: 28a426b66893f49668ade30c220d46caa7313fa71dc43c7a44c7f0967e28a5dfd9e1321965fdc0a1b665607b9b46d856207d0bde2af06f77de0d400def8b7071

test:
  secret_key_base: 28a426b66893f49668ade30c220d46caa7313fa71dc43c7a44c7f0967e28a5dfd9e1321965fdc0a1b665607b9b46d856207d0bde2af06f77de0d400def8b7071
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
